### ISSUE TITLE
Run png2mem on windows

### ISSUE THREAD

**Issue by MouvementMondial** [trebb/phoros#1]
Hello, I have implemented your functions for reading the containerfile under windows with mingw. It seems to work well, but in line 544 of imread.c the mode 'r' should be changed to 'rb'. Just in case someone still uses the library with windows.

See also:
http://stackoverflow.com/questions/164002/why-is-fread-reaching-the-eof-early

Thank you for providing the code!

Regards,
MouvementMondial

**Comment by trebb** [comment]
Thanks for the report; I've committed the fix as suggested.
